### PR TITLE
Add C/C++ coding standards

### PR DESCRIPTION
**Pull request by AlexP11223**

### CODE REVIEW

**Comment by Kristories** [comment]
Thank you! But GNU is already in the "GNU" section. Please check, it is the same content.

[Making The Best Use of C](https://www.gnu.org/prep/standards/html_node/Writing-C.html) - This chapter provides advice on how best to use the C language when writing GNU software.

**Comment by AlexP11223** [comment]
hm, maybe it makes sense to keep only the first link in the GNU section and move the C link to languages?

**Comment by Kristories** [comment]
Make sense. I reopen this. Please make a change.

**Review by Kristories — APPROVED** [review]

**Comment by Kristories** [comment]
💯 Looks great. Thanks for your contribution! I'll deploy this as soon as CI is.

**Pull request merged**
