### PR TITLE
Add: GNU Pascal Coding Standards guide

### PR DESCRIPTION
**Pull request by rilysh**
Automated note: By submitting this pull request, I promise I have read the [contribution guidelines](https://github.com/Kristories/awesome-guidelines/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖

### CODE REVIEW

**Comment by putrisepty** [comment]
@Kristories kirimin uang buat anaknya sekolah dan makan

**Comment by putrisepty** [comment]
Klo papah mau jaga image jangan keputusan sepihakk

**Comment by putrisepty** [comment]
@Kristories bajingan

**Comment by putrisepty** [comment]
@Kristories klo ortu aku mati kamu orang pertama yanv mamah kejarrrrr!

**Review by Kristories — APPROVED** [review]

**Pull request merged**
